apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: apache1
  replicas: 3
  selector:
    matchLabels:
      type: front-end

// service
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30000

  selector:
    app: pod-deployment  
    type: front-end
